# test with cov
name: Test Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  test-coverage:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.4.0'

      - name: Configure R options (macOS & Windows)
        if: matrix.os != 'ubuntu-latest'
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          if (.Platform$OS.type == "unix") {
            options(pkgType = "binary")
          }
        shell: Rscript {0}

      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage

      - name: Test coverage
        run: |
          dir.create("coverage", showWarnings = FALSE)
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          covr::to_cobertura(cov, "coverage/cobertura.xml")
        shell: Rscript {0}

      - name: Verificar archivos generados
        run: ls -l coverage/

      - uses: codecov/codecov-action@v4.1.0
        with:
          fail_ci_if_error: true
          file: coverage/cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures-${{ matrix.os }}
          path: coverage/
